const fs=require('fs');
const h=fs.readFileSync('D:/Projects/caddy-ed-cadillac-hugo/site/public/inventory/2026-cadillac-xt5-luxury/index.html','utf8');
const pick=(re)=>{ const m=h.match(re); return m ? (m[1]||m[0]).slice(0,72) : '(none)'; };
console.log('  <title>          ' + pick(/<title>([^<]*)/));
console.log('  og:title         ' + pick(/og:title" content="([^"]*)/));
console.log('  twitter:title    ' + pick(/twitter:title" content="([^"]*)/));
console.log('  breadcrumb       ' + pick(/aria-current=page>([^<]*)/));
console.log('  h1               ' + pick(/<h1[^>]*>([^<]*)/));
console.log('  JSON-LD name     ' + pick(/"name":"([^"]*)/));
console.log('  booking line     ' + pick(/<strong>([^<]*XT5[^<]*)/));
console.log('  image alt        ' + pick(/alt="(2026 CADILLAC[^"]*)/));
console.log('');
console.log('  parenthesised stock refs left anywhere: ' + ([...h.matchAll(/\(#[A-Z0-9]+\)/g)].length));
console.log('  deliberate "Stock NTZ..." in the spec row: ' + ([...h.matchAll(/Stock NTZ/g)].length));
