[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.121.1"
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:preview"

# Redirects and rewrites
[[redirects]]
  from = "/api/inventory/*"
  to = "/.netlify/functions/inventory-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app netlify-cdp-loader.netlify.app; img-src 'self' data: *.cloudfront.net; connect-src 'self' *.netlify.app;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.(?:jpg|jpeg|gif|png|svg|webp)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://caddyed.netlify.app"
    sitemapPath = "/sitemap.xml"
