[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.121.1"
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:preview"

# Redirects and rewrite rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.netlify.app *.cadillacofsouthcharlotte.com *.googleapis.com *.gstatic.com *.google-analytics.com *.googletagmanager.com *.youtube.com *.facebook.net *.facebook.com;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    baseUrl = "https://caddyed.com"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing"
    ]

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
  [plugins.inputs]
    cacheDigest = true
    cacheEntries = true
    cacheNextConfig = true
    customPaths = [
      ".cache",
      "site/resources"
    ]
