baseURL = "https://caddyed.com/"
languageCode = "en-us"
title = "Caddy Ed Cadillac - South Charlotte Cadillac Dealer"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Caddy Ed is your trusted Cadillac dealer in South Charlotte. Browse our inventory of new and used Cadillac vehicles, schedule service, or contact our dealership today."
  author = "Caddy Ed"
  phone = "(704) 555-1234"
  address = "1234 Cadillac Drive, Charlotte, NC 28210"
  email = "sales@caddyed.com"
  hours = "Monday-Friday: 9AM-8PM, Saturday: 9AM-6PM, Sunday: Closed"
  
  # Social Media Links
  facebook = "https://facebook.com/caddyed"
  instagram = "https://instagram.com/caddyed"
  twitter = "https://twitter.com/caddyed"
  youtube = "https://youtube.com/caddyed"
  
  # Google Maps API Key
  mapsApiKey = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Inventory"
    url = "/inventory/"
    weight = 2
  [[menu.main]]
    name = "New Vehicles"
    url = "/inventory/new/"
    parent = "Inventory"
    weight = 1
  [[menu.main]]
    name = "Pre-Owned"
    url = "/inventory/used/"
    parent = "Inventory"
    weight = 2
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Financing"
    url = "/financing/"
    weight = 4
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"
  model = "models"
  year = "years"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[minify]
  minifyOutput = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
