baseURL: "https://caddyed.com"
languageCode: "en-us"
title: "Caddy Ed - Cadillac of South Charlotte"
theme: "cadillac"
enableGitInfo: true
enableRobotsTXT: true

params:
  description: "Your trusted Cadillac dealer in Charlotte NC. Meet Caddy Ed, your personal Cadillac expert with over 20 years of experience."
  images: ["img/og-image.jpg"]
  social:
    facebook: "https://facebook.com/caddyedcharlotte"
    instagram: "https://instagram.com/caddyed"
    youtube: "https://youtube.com/channel/caddyed"
  contact:
    email: "ed@caddyed.com"
    phone: "(704) 555-1234"
    address: "9315 E Independence Blvd, Matthews, NC 28105"
  googleAnalytics: "G-XXXXXXXXXX"
  dealershipAPI: 
    baseURL: "https://www.cadillacofsouthcharlotte.com/apis"
    inventoryEndpoint: "/inventory"
  features:
    enableLiveInventory: true
    enableTestDriveBooking: true
    enableTradeInCalculator: true

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Inventory"
      url: "/inventory/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
    - name: "Services"
      url: "/services/"
      weight: 4
    - name: "Contact"
      url: "/contact/"
      weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true

caches:
  getjson:
    maxAge: "10m"
  getcsv:
    maxAge: "10m"
  images:
    maxAge: "24h"

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

# Disable unwanted sections
disableKinds: ["RSS", "taxonomy", "taxonomyTerm"]

# Set up asset handling
build:
  writeStats: true
  
# Pagination
paginate: 12
