baseURL = "/"
languageCode = "en-us"
title = "Caddy Ed - Cadillac Sales Specialist"
enableRobotsTXT = true
disableKinds = ["RSS"]

[params]
  description = "Caddy Ed - Your Cadillac Sales Specialist in South Charlotte. New & Pre-Owned Cadillac inventory, test drives, and trade-in valuations."
  images = ["img/caddy-ed-logo.jpg"]
  title = "Caddy Ed - Cadillac Sales Specialist"
  dealer_name = "Cadillac of South Charlotte"
  phone = "704-555-1234"
  email = "ed@caddyed.com"
  address = "123 Cadillac Drive, Charlotte, NC 28210"
  hours = "Mon-Fri: 9AM-7PM | Sat: 9AM-5PM | Sun: Closed"
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "inventory"
    name = "Inventory"
    url = "/inventory/"
    weight = 2
  [[menu.main]]
    identifier = "specials"
    name = "Specials"
    url = "/specials/"
    weight = 3
  [[menu.main]]
    identifier = "financing"
    name = "Financing"
    url = "/financing/"
    weight = 4
  [[menu.main]]
    identifier = "trade-in"
    name = "Trade-In"
    url = "/trade-in/"
    weight = 5
  [[menu.main]]
    identifier = "about"
    name = "About Ed"
    url = "/about/"
    weight = 6
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 7

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
