baseURL: "/"
languageCode: "en-us"
title: "Caddy Ed Cadillac | Luxury Vehicles & Service"
theme: "cadillac"
enableGitInfo: true
enableRobotsTXT: true

params:
  description: "Caddy Ed Cadillac offers premium Cadillac vehicles and expert service. Visit our showroom today!"
  images: ["img/og-image.jpg"]
  
  # Contact Information
  contact:
    phone: "(555) 123-4567"
    email: "info@caddyed.com"
    address: "123 Luxury Drive, Anytown, USA 12345"
    hours: "Monday-Friday: 9am-8pm, Saturday: 10am-6pm, Sunday: Closed"
    
  # Social Media
  social:
    facebook: "https://facebook.com/caddyed"
    instagram: "https://instagram.com/caddyed"
    twitter: "https://twitter.com/caddyed"
    youtube: "https://youtube.com/caddyed"
    
  # Google Analytics
  googleAnalytics: ""
  
  # Featured Models
  featuredModels:
    - name: "Escalade"
      image: "img/models/escalade.jpg"
      url: "/models/escalade/"
    - name: "CT5"
      image: "img/models/ct5.jpg"
      url: "/models/ct5/"
    - name: "XT5"
      image: "img/models/xt5.jpg"
      url: "/models/xt5/"
  dealershipAPI: 
    baseURL: "https://www.cadillacofsouthcharlotte.com/apis"
    inventoryEndpoint: "/inventory"
  features:
    enableLiveInventory: true
    enableTestDriveBooking: true
    enableTradeInCalculator: true

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Inventory"
      url: "/inventory/"
      weight: 2
    - name: "About"
      url: "/about/"
      weight: 3
    - name: "Services"
      url: "/services/"
      weight: 4
    - name: "Contact"
      url: "/contact/"
      weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true

caches:
  getjson:
    maxAge: "10m"
  getcsv:
    maxAge: "10m"
  images:
    maxAge: "24h"

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

# Disable unwanted sections
disableKinds: ["taxonomy", "taxonomyTerm"]

# Set up asset handling
build:
  writeStats: true
  
# Pagination
paginate: 12
