backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

local_backend: true
media_folder: "site/static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Subtitle", name: "subtitle", widget: "string", required: false},
              {label: "Call to Action", name: "cta", widget: "object", required: false, fields: [
                {label: "Text", name: "text", widget: "string"},
                {label: "Link", name: "link", widget: "string"}
              ]}
            ]}
          - {label: "About Section", name: "about", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Text", name: "text", widget: "markdown"}
            ]}
          - {label: "Featured Section", name: "featured", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Items", name: "items", widget: "list", fields: [
                {label: "Image", name: "image", widget: "image"},
                {label: "Title", name: "title", widget: "string"},
                {label: "Description", name: "description", widget: "text"}
              ]}
            ]}
          - {label: "Testimonials Section", name: "testimonials", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Items", name: "items", widget: "list", fields: [
                {label: "Quote", name: "quote", widget: "text"},
                {label: "Author", name: "author", widget: "string"}
              ]}
            ]}

      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Team Members", name: "team", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Position", name: "position", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Bio", name: "bio", widget: "text"}
            ]}

      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Items", name: "items", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Price", name: "price", widget: "number", required: false}
            ]}

      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Values", name: "values", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Text", name: "text", widget: "text"},
              {label: "Image", name: "image", widget: "image"}
            ]}

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Address", name: "address", widget: "text", required: false}
          - {label: "Business Hours", name: "hours", widget: "text", required: false}
          - {label: "Map Embed Code", name: "map", widget: "text", required: false}

  - name: "inventory"
    label: "Inventory Items"
    folder: "site/content/inventory"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Publish Date", name: date, widget: datetime}
      - {label: Price, name: price, widget: string}
      - {label: Year, name: year, widget: number}
      - {label: Make, name: make, widget: string}
      - {label: Model, name: model, widget: string}
      - {label: Trim, name: trim, widget: string, required: false}
      - {label: Mileage, name: mileage, widget: number}
      - {label: "Featured Image", name: featured_image, widget: image}
      - {label: "Gallery Images", name: gallery, widget: list, field: {label: Image, name: image, widget: image}}
      - {label: Description, name: description, widget: markdown}
      - {label: Features, name: features, widget: list}

  - name: "blog"
    label: "Blog"
    folder: "site/content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "testimonials"
    label: "Testimonials"
    folder: "site/content/testimonials"
    create: true
    fields:
      - {label: "Customer Name", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Customer Image", name: "customerImage", widget: "image", required: false}
      - {label: "Vehicle Purchased", name: "vehicle", widget: "string"}
      - {label: "Testimonial", name: "body", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "specials"
    label: "Special Offers"
    folder: "site/content/specials"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Expiration Date", name: "expirationDate", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Terms & Conditions", name: "terms", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "settings"
    label: "Settings"
    files:
      - file: "site/data/settings.json"
        label: "Site Settings"
        name: "settings"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Contact Email", name: "contactEmail", widget: "string"}
          - {label: "Contact Phone", name: "contactPhone", widget: "string"}
          - {label: "Social Media", name: "socialMedia", widget: "object", fields: [
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false},
              {label: "Twitter/X", name: "twitter", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "YouTube", name: "youtube", widget: "string", required: false}
            ]}
          - {label: "Google Maps URL", name: "googleMapsUrl", widget: "string", required: false}