backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

local_backend: true
media_folder: "site/static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Call to Action", name: cta, widget: object, fields: [
              {label: Text, name: text, widget: string},
              {label: Link, name: link, widget: string}
            ]}
          - {label: "Introduction", name: intro, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Text, name: text, widget: text}
            ]}
          - {label: "Inventory Section", name: inventory, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Text, name: text, widget: text}
            ]}
          - {label: "Testimonials", name: testimonials, widget: object, fields: [
              {label: Heading, name: heading, widget: string},
              {label: Items, name: items, widget: list, fields: [
                {label: Quote, name: quote, widget: text},
                {label: Author, name: author, widget: string}
              ]}
            ]}

      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Team Members", name: "team", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Position", name: "position", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Bio", name: "bio", widget: "text"}
            ]}
          - {label: "Experience", name: "experience", widget: "list", fields: [
              {label: "Year", name: "year", widget: "string"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"}
            ]}

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Contact Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Hours", name: "hours", widget: "text"}
          - {label: "Map Embed", name: "map", widget: "text", required: false}
          - {label: "Intro", name: "intro", widget: "text"}

  - name: "inventory"
    label: "Inventory Items"
    folder: "site/content/inventory"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Publish Date", name: date, widget: datetime}
      - {label: Price, name: price, widget: string}
      - {label: Year, name: year, widget: number}
      - {label: Make, name: make, widget: string}
      - {label: Model, name: model, widget: string}
      - {label: Trim, name: trim, widget: string, required: false}
      - {label: Mileage, name: mileage, widget: number}
      - {label: "Featured Image", name: featured_image, widget: image}
      - {label: "Gallery Images", name: gallery, widget: list, field: {label: Image, name: image, widget: image}}
      - {label: Description, name: description, widget: markdown}
      - {label: Features, name: features, widget: list}

  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: "Publish Date", name: date, widget: datetime}
      - {label: Author, name: author, widget: string, required: false}
      - {label: "Featured Image", name: featured_image, widget: image, required: false}
      - {label: Description, name: description, widget: text}
      - {label: Body, name: body, widget: markdown}

  - name: "testimonials"
    label: "Testimonials"
    folder: "site/content/testimonials"
    create: true
    fields:
      - {label: "Customer Name", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Customer Image", name: "customerImage", widget: "image", required: false}
      - {label: "Vehicle Purchased", name: "vehicle", widget: "string"}
      - {label: "Testimonial", name: "body", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "specials"
    label: "Special Offers"
    folder: "site/content/specials"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Expiration Date", name: "expirationDate", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Terms & Conditions", name: "terms", widget: "markdown"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "settings"
    label: "Settings"
    files:
      - file: "site/data/settings.json"
        label: "Site Settings"
        name: "settings"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Contact Email", name: "contactEmail", widget: "string"}
          - {label: "Contact Phone", name: "contactPhone", widget: "string"}
          - {label: "Social Media", name: "socialMedia", widget: "object", fields: [
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false},
              {label: "Twitter/X", name: "twitter", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "YouTube", name: "youtube", widget: "string", required: false}
            ]}
          - {label: "Google Maps URL", name: "googleMapsUrl", widget: "string", required: false}