backend:
  name: git-gateway
  branch: main

# Publish mode enables review workflow
publish_mode: editorial_workflow

# Media and public folders
media_folder: "site/static/img"
public_folder: "/img"

collections:
  - name: "inventory"
    label: "Inventory"
    folder: "site/content/inventory"
    create: true
    slug: "{{year}}-{{make}}-{{model}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "VIN", name: "vin", widget: "string"}
      - {label: "Make", name: "make", widget: "string"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Trim", name: "trim", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Mileage", name: "mileage", widget: "number"}
      - {label: "Exterior Color", name: "exteriorColor", widget: "string"}
      - {label: "Interior Color", name: "interiorColor", widget: "string"}
      - {label: "Engine", name: "engine", widget: "string"}
      - {label: "Transmission", name: "transmission", widget: "string"}
      - {label: "Drivetrain", name: "drivetrain", widget: "string"}
      - {label: "Fuel Type", name: "fuelType", widget: "string"}
      - {label: "Stock Number", name: "stockNumber", widget: "string"}
      - {label: "Images", name: "images", widget: "list", field: {label: Image URL, name: url, widget: string}}
      - {label: "Features", name: "features", widget: "list", field: {label: Feature, name: feature, widget: string}}
      - {label: "Description", name: "body", widget: "markdown"}
      
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Hero Image", name: "image", widget: "image"}
          - {label: "Hero Heading", name: "heading", widget: "string"}
          - {label: "Hero Subheading", name: "subheading", widget: "string"}
          - {label: "Featured Models", name: "featured", widget: "list", fields: [
              {label: "Model", name: "model", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Description", name: "description", widget: "text"}
            ]}
          - {label: "Intro", name: "intro", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Text", name: "text", widget: "text"}
            ]}
          - {label: "Testimonials", name: "testimonials", widget: "list", fields: [
              {label: "Quote", name: "quote", widget: "string"},
              {label: "Author", name: "author", widget: "string"}
            ]}
      
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Contact Email", name: "email", widget: "string"}
      
      - file: "site/content/service/_index.md"
        label: "Service Page"
        name: "service"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Service Options", name: "services", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Image", name: "image", widget: "image"}
            ]}

  - name: "specials"
    label: "Special Offers"
    folder: "site/content/specials"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Expiration Date", name: "expirationDate", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      
  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "vehicles"
    label: "Featured Vehicles"
    folder: "site/content/vehicles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "MSRP", name: "msrp", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Features", name: "features", widget: "list"}
      - {label: "Specifications", name: "specs", widget: "markdown"}
      - {label: "Condition", name: "condition", widget: "select", options: ["New", "Used", "Certified Pre-Owned"]}
      - {label: "Stock Number", name: "stock", widget: "string"}
      - {label: "VIN", name: "vin", widget: "string"}
      - {label: "Mileage", name: "mileage", widget: "number"}
      - {label: "Fuel Economy", name: "mpg", widget: "string"}
      - {label: "Body Style", name: "bodyStyle", widget: "string"}
      - {label: "Exterior Color", name: "exteriorColor", widget: "string"}
      - {label: "Interior Color", name: "interiorColor", widget: "string"}
      - {label: "Transmission", name: "transmission", widget: "string"}
      - {label: "Engine", name: "engine", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}