backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

local_backend: true
media_folder: site/static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Hero Image", name: "image", widget: "image"}
          - {label: "Hero Heading", name: "heading", widget: "string"}
          - {label: "Hero Subheading", name: "subheading", widget: "string"}
          - {label: "Call to Action Text", name: "cta", widget: "string"}
          - {label: "Call to Action Link", name: "cta_link", widget: "string"}
          - {label: "Featured Models Section", name: "featured_models", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Text", name: "text", widget: "text"},
              {label: "Models", name: "models", widget: "list", fields: [
                {label: "Model Name", name: "name", widget: "string"},
                {label: "Image", name: "image", widget: "image"},
                {label: "Text", name: "text", widget: "text"},
                {label: "Link", name: "link", widget: "string"}
              ]}
            ]}
          - {label: "Testimonials", name: "testimonials", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Position", name: "position", widget: "string", required: false},
              {label: "Image", name: "image", widget: "image", required: false},
              {label: "Text", name: "text", widget: "text"}
            ]}
          - {label: "Services Section", name: "services", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Text", name: "text", widget: "text"},
              {label: "Services List", name: "items", widget: "list", fields: [
                {label: "Title", name: "title", widget: "string"},
                {label: "Icon", name: "icon", widget: "string"},
                {label: "Text", name: "text", widget: "text"}
              ]}
            ]}
      
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Team Members", name: "team", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Position", name: "position", widget: "string"},
              {label: "Image", name: "image", widget: "image"},
              {label: "Bio", name: "bio", widget: "text"}
            ]}

      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Contact Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Hours", name: "hours", widget: "text"}
          - {label: "Map Embed", name: "map", widget: "text", required: false}

  - name: "inventory"
    label: "Featured Inventory"
    folder: "site/content/inventory"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Gallery Images", name: "gallery", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Year", name: "year", widget: "number"}
      - {label: "Make", name: "make", widget: "string", default: "Cadillac"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "Trim", name: "trim", widget: "string", required: false}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "MSRP", name: "msrp", widget: "number", required: false}
      - {label: "Mileage", name: "mileage", widget: "number"}
      - {label: "Exterior Color", name: "exterior_color", widget: "string"}
      - {label: "Interior Color", name: "interior_color", widget: "string"}
      - {label: "Stock #", name: "stock", widget: "string"}
      - {label: "VIN", name: "vin", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Features", name: "features", widget: "list"}
      - {label: "Is Featured", name: "is_featured", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "blog"
    label: "Blog"
    folder: "site/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}