-- turso/001_core.sql -- GENERATED by scripts/pg2turso.py. Do not hand-edit.
--
-- The libSQL/Turso translation of database/migrations/{001,004,005}.
--
--   Apply with:  npm run db:push
--   Or by hand:  sqlite3 local.db < database/turso/001_core.sql
--
-- Translated: SERIAL, TIMESTAMPTZ, UUID, JSONB, BOOLEAN, NUMERIC, TEXT[]
-- Dropped:     triggers, plpgsql functions, views, GIN/tsvector indexes
--
-- The dropped items are search and automation machinery, not data. Every column
-- a trigger would have maintained is written by the function that owns it.
-- Full-text search falls back to LIKE. See docs/STORAGE.md for the consequences
-- and for what is not covered.

CREATE TABLE IF NOT EXISTS appointments (
  id TEXT PRIMARY KEY,
  customer_id TEXT,
  lead_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  scheduled_start TEXT NOT NULL,
  scheduled_end TEXT NOT NULL,
  duration_minutes TEXT,
  timezone TEXT DEFAULT 'America/New_York',
  location TEXT DEFAULT 'Cadillac of South Charlotte',
  address TEXT,
  meeting_link TEXT,
  assigned_sales_rep_id TEXT,
  assigned_sales_rep_name TEXT,
  additional_attendees TEXT,
  vehicle_of_interest TEXT,
  vehicle_stock_number TEXT,
  preparation_notes TEXT,
  customer_notes TEXT,
  outcome TEXT,
  follow_up_actions TEXT,
  next_appointment_id TEXT,
  reminder_sent TEXT DEFAULT false,
  reminder_count TEXT DEFAULT 0,
  last_reminder_sent TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  completed_at TEXT
);

CREATE TABLE IF NOT EXISTS communication_preference_log (
  id TEXT PRIMARY KEY,
  customer_id TEXT,
  changes TEXT NOT NULL,
  source TEXT DEFAULT 'customer_portal',
  ip_address TEXT,
  user_agent TEXT,
  session_id TEXT,
  notes TEXT,
  processed_by TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS customer_vehicle_interest (
  id TEXT PRIMARY KEY,
  customer_id TEXT,
  vehicle_id TEXT,
  notes TEXT,
  pros TEXT,
  cons TEXT,
  questions TEXT,
  budget_range TEXT,
  financing_preapproved TEXT DEFAULT false,
  trade_in_interest TEXT DEFAULT false,
  purchase_timeline TEXT,
  preferred_test_drive_dates TEXT,
  last_discussed TEXT,
  sales_rep_notes TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS customers (
  id TEXT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  phone_type TEXT DEFAULT 'mobile',
  address_line1 TEXT,
  address_line2 TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  country TEXT DEFAULT 'USA',
  customer_type TEXT DEFAULT 'prospect' CHECK (customer_type IN ('prospect', 'lead', 'active', 'inactive', 'vip')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'archived', 'do_not_contact')),
  source TEXT DEFAULT 'website',
  preferred_vehicle_type TEXT,
  budget_min TEXT,
  budget_max TEXT,
  preferred_contact_method TEXT DEFAULT 'email' CHECK (preferred_contact_method IN ('email', 'phone', 'sms', 'mail')),
  assigned_sales_rep_id TEXT,
  assigned_sales_rep_name TEXT,
  lead_score TEXT DEFAULT 0,
  last_activity_date TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  email_consent TEXT DEFAULT false,
  sms_consent TEXT DEFAULT false,
  phone_consent TEXT DEFAULT false,
  gdpr_consent_date TEXT,
  do_not_contact_reason TEXT,
  normalized_email TEXT,
  normalized_phone TEXT,
  normalized_name TEXT,
  duplicate_count TEXT DEFAULT 0,
  merged_from TEXT DEFAULT '{}',
  merged_into TEXT
);

CREATE TABLE IF NOT EXISTS email_templates (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  content TEXT NOT NULL,
  is_active TEXT DEFAULT true,
  variables TEXT DEFAULT '[]',
  usage_count TEXT DEFAULT 0,
  last_used TEXT,
  preview_text TEXT,
  test_email TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS followup_analytics (
  id TEXT PRIMARY KEY,
  followup_id TEXT,
  customer_id TEXT,
  campaign_id TEXT,
  event_timestamp TEXT DEFAULT (datetime('now')),
  email_opened TEXT DEFAULT false,
  link_clicked TEXT,
  user_agent TEXT,
  ip_address TEXT,
  location_data TEXT,
  campaign_name TEXT,
  template_name TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS followup_campaigns (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  is_active TEXT DEFAULT true,
  priority TEXT DEFAULT 1,
  start_date TEXT,
  end_date TEXT,
  timezone TEXT DEFAULT 'America/New_York',
  total_sent TEXT DEFAULT 0,
  total_opened TEXT DEFAULT 0,
  total_clicked TEXT DEFAULT 0,
  total_converted TEXT DEFAULT 0,
  total_unsubscribed TEXT DEFAULT 0,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS followup_rules (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  trigger_event TEXT NOT NULL,
  conditions TEXT DEFAULT '{}',
  customer_conditions TEXT DEFAULT '{}',
  lead_conditions TEXT DEFAULT '{}',
  interaction_conditions TEXT DEFAULT '{}',
  actions TEXT DEFAULT '[]',
  campaign_id TEXT,
  campaign_name TEXT,
  priority TEXT DEFAULT 1,
  delay_hours TEXT DEFAULT 0,
  is_active TEXT DEFAULT true,
  start_date TEXT,
  end_date TEXT,
  days_of_week TEXT,
  time_range_start TEXT,
  time_range_end TEXT,
  business_hours_only TEXT DEFAULT false,
  trigger_count TEXT DEFAULT 0,
  success_count TEXT DEFAULT 0,
  failure_count TEXT DEFAULT 0,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS followups (
  id TEXT PRIMARY KEY,
  customer_id TEXT,
  lead_id TEXT,
  campaign_id TEXT,
  rule_id TEXT,
  campaign_name TEXT,
  email TEXT DEFAULT false,
  sms TEXT DEFAULT false,
  email_template TEXT,
  sms_template TEXT,
  scheduled_date TEXT NOT NULL,
  sent_date TEXT,
  priority TEXT DEFAULT 1,
  skip_reason TEXT,
  error_message TEXT,
  email_consent TEXT DEFAULT false,
  sms_consent TEXT DEFAULT false,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT
);

CREATE TABLE IF NOT EXISTS interactions (
  id TEXT PRIMARY KEY,
  customer_id TEXT,
  lead_id TEXT,
  direction TEXT DEFAULT 'outbound' CHECK (direction IN ('inbound', 'outbound')),
  subject TEXT,
  content TEXT,
  summary TEXT,
  initiated_by TEXT,
  sales_rep_id TEXT,
  sales_rep_name TEXT,
  contact_method TEXT,
  contact_details TEXT,
  outcome TEXT,
  next_action TEXT,
  next_action_date TEXT,
  duration_minutes TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS leads (
  id TEXT PRIMARY KEY,
  customer_id TEXT,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  message TEXT,
  form_type TEXT DEFAULT 'general',
  lead_source TEXT DEFAULT 'website',
  page_url TEXT,
  vehicle_interest TEXT,
  vehicle_year TEXT,
  vehicle_make TEXT,
  vehicle_model TEXT,
  vehicle_trim TEXT,
  vehicle_stock_number TEXT,
  vehicle_price TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'qualified', 'converted', 'lost', 'duplicate')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  score TEXT DEFAULT 0,
  assigned_sales_rep_id TEXT,
  assigned_sales_rep_name TEXT,
  next_follow_up_date TEXT,
  follow_up_count TEXT DEFAULT 0,
  converted_to_customer TEXT DEFAULT false,
  conversion_date TEXT,
  conversion_value TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  last_contact TEXT DEFAULT (datetime('now')),
  normalized_email TEXT,
  normalized_phone TEXT,
  normalized_name TEXT,
  duplicate_count TEXT DEFAULT 0,
  merged_from TEXT DEFAULT '{}',
  merged_into TEXT
);

CREATE TABLE IF NOT EXISTS sales_reps (
  id TEXT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password_hash TEXT,
  employee_id TEXT UNIQUE,
  role TEXT DEFAULT 'sales_representative',
  department TEXT DEFAULT 'sales',
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'on_leave', 'terminated')),
  permissions TEXT DEFAULT 'view_customers,manage_leads',
  hire_date TEXT,
  current_lead_count TEXT DEFAULT 0,
  current_customer_count TEXT DEFAULT 0,
  monthly_sales_target TEXT,
  specializations TEXT,
  languages TEXT DEFAULT 'english',
  preferred_contact_method TEXT DEFAULT 'email',
  working_hours TEXT DEFAULT '{"monday": {"start": "09:00", "end": "18:00"}, "tuesday": {"start": "09:00", "end": "18:00"}, "wednesday": {"start": "09:00", "end": "18:00"}, "thursday": {"start": "09:00", "end": "18:00"}, "friday": {"start": "09:00", "end": "18:00"}, "saturday": {"start": "09:00", "end": "17:00"}, "sunday": null}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  last_login TEXT,
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS sms_templates (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  is_active TEXT DEFAULT true,
  character_count TEXT,
  variables TEXT DEFAULT '[]',
  usage_count TEXT DEFAULT 0,
  last_used TEXT,
  test_phone TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  assigned_to TEXT,
  assigned_to_name TEXT,
  customer_id TEXT,
  lead_id TEXT,
  appointment_id TEXT,
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  due_date TEXT,
  completed_date TEXT,
  estimated_duration_minutes TEXT,
  actual_duration_minutes TEXT,
  tags TEXT,
  checklist TEXT DEFAULT '[]',
  attachments TEXT,
  outcome TEXT,
  lessons_learned TEXT,
  is_recurring TEXT DEFAULT false,
  recurrence_pattern TEXT,
  next_occurrence TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT
);

CREATE TABLE IF NOT EXISTS vehicles (
  id TEXT PRIMARY KEY,
  stock_number TEXT UNIQUE NOT NULL,
  vin TEXT UNIQUE,
  year TEXT NOT NULL,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  trim TEXT,
  body_style TEXT,
  exterior_color TEXT,
  interior_color TEXT,
  engine TEXT,
  transmission TEXT,
  drivetrain TEXT,
  fuel_type TEXT,
  mileage TEXT,
  list_price TEXT,
  sale_price TEXT,
  msrp TEXT,
  features TEXT,
  packages TEXT,
  image_urls TEXT,
  video_url TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  date_in_stock TEXT,
  date_sold TEXT
);

CREATE INDEX IF NOT EXISTS idx_leads_status        ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_customer      ON leads(customer_id);
CREATE INDEX IF NOT EXISTS idx_leads_created       ON leads(created_at);
CREATE INDEX IF NOT EXISTS idx_interactions_cust   ON interactions(customer_id);
CREATE INDEX IF NOT EXISTS idx_interactions_lead   ON interactions(lead_id);
CREATE INDEX IF NOT EXISTS idx_interactions_when  ON interactions(created_at);
CREATE INDEX IF NOT EXISTS idx_appts_cust          ON appointments(customer_id);
CREATE INDEX IF NOT EXISTS idx_appts_start         ON appointments(scheduled_start);
CREATE INDEX IF NOT EXISTS idx_appts_rep           ON appointments(assigned_sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_followups_lead      ON followups(lead_id);
CREATE INDEX IF NOT EXISTS idx_followups_cust      ON followups(customer_id);
CREATE INDEX IF NOT EXISTS idx_followups_sched     ON followups(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_reps_email          ON sales_reps(email);
CREATE INDEX IF NOT EXISTS idx_reps_status         ON sales_reps(status);
