-- turso/002_app_columns.sql -- GENERATED by scripts/schema-audit.py.
--
-- Columns the FUNCTIONS query that database/migrations/ never created.
--
-- Found by running the application's real statements against the
-- generated schema: 8 of 14 failed with "no such column". The Postgres
-- migrations and the function code disagree about the schema, so this
-- would not have worked on Postgres either -- it only became visible
-- because the queries were executed rather than parsed.
--
-- Types are inferred from the sibling columns in the same table and
-- default to TEXT, which is what the code already treats them as.

-- appointments
ALTER TABLE appointments ADD COLUMN appointment_type TEXT;
ALTER TABLE appointments ADD COLUMN notes TEXT;
ALTER TABLE appointments ADD COLUMN sales_rep_id INTEGER;
ALTER TABLE appointments ADD COLUMN scheduled_date INTEGER;
ALTER TABLE appointments ADD COLUMN scheduled_time INTEGER;
ALTER TABLE appointments ADD COLUMN status TEXT;

-- communication_preference_log
ALTER TABLE communication_preference_log ADD COLUMN action TEXT;

-- customers
ALTER TABLE customers ADD COLUMN communication_preferences TEXT;
ALTER TABLE customers ADD COLUMN consent_date INTEGER;
ALTER TABLE customers ADD COLUMN consent_source TEXT;
ALTER TABLE customers ADD COLUMN consent_withdrawn_date INTEGER;
ALTER TABLE customers ADD COLUMN consent_withdrawn_reason TEXT;
ALTER TABLE customers ADD COLUMN gdpr_consent_withdrawn TEXT;
ALTER TABLE customers ADD COLUMN preferences TEXT;

-- email_templates
ALTER TABLE email_templates ADD COLUMN template_type TEXT;

-- followup_analytics
ALTER TABLE followup_analytics ADD COLUMN event_type TEXT;

-- followup_campaigns
ALTER TABLE followup_campaigns ADD COLUMN campaign_type TEXT;

-- followups
ALTER TABLE followups ADD COLUMN status TEXT;

-- interactions
ALTER TABLE interactions ADD COLUMN description TEXT;
ALTER TABLE interactions ADD COLUMN interaction_type TEXT;
ALTER TABLE interactions ADD COLUMN notes TEXT;

-- leads
ALTER TABLE leads ADD COLUMN sales_rep_notes TEXT;

-- sales_reps
ALTER TABLE sales_reps ADD COLUMN image TEXT;
ALTER TABLE sales_reps ADD COLUMN name TEXT;
ALTER TABLE sales_reps ADD COLUMN position TEXT;

-- sms_templates
ALTER TABLE sms_templates ADD COLUMN template_type TEXT;

