-- schema.sql -- GENERATED by scripts/build-schema.py. Do not edit by hand.
--
-- The complete libSQL schema for caddyed.com. One file, applied in one go.
--
-- It supersedes applying 001 + 002 + 003 + 004 in order, which is how this
-- schema was actually arrived at: each of those four fixed something real, and
-- each was a discovery rather than a plan. That is normal, and it is also the
-- worst thing to leave behind -- four ordered files where the last contradicts
-- the first, and a reader of 001 cannot tell what the real shape is.
--
-- 001..003 are kept as the record of how it got here. This file is the truth.
--
--   tables   21
--   foreign keys 22   (an audit found zero)
--   indexes  ~50
--
-- PRAGMA
-- ------
-- SQLite does not enforce foreign keys unless asked, and libSQL is SQLite:
-- `PRAGMA foreign_keys` defaults to OFF. The constraints below are therefore
-- correct and INERT unless a connection enables it. database-service.js issues
-- the pragma on every connection, which is what makes them real.
--
-- If that line is ever removed, every constraint in this file silently stops
-- being true and nothing fails -- the schema still looks right and the guarantee
-- is gone. To check on a live connection:
--
--     PRAGMA foreign_keys;        -- expect 1
--     PRAGMA foreign_key_check;   -- expect no rows
--
-- IDS
-- ---
-- Every id is TEXT and every one is generated by the application
-- (DatabaseService.newId), not by a schema default. There is no expression that
-- is a valid default on both libSQL and Postgres, and this project reaches both
-- through one data path -- so it is made in JavaScript, where it means the same
-- thing either way.

PRAGMA foreign_keys = ON;


CREATE TABLE IF NOT EXISTS appointments (

  id TEXT PRIMARY KEY,
  customer_id TEXT,
  lead_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  scheduled_start TEXT NOT NULL,
  scheduled_end TEXT NOT NULL,
  duration_minutes TEXT,
  timezone TEXT DEFAULT 'America/New_York',
  location TEXT DEFAULT 'Cadillac of South Charlotte',
  address TEXT,
  meeting_link TEXT,
  assigned_sales_rep_id TEXT,
  assigned_sales_rep_name TEXT,
  additional_attendees TEXT,
  vehicle_of_interest TEXT,
  vehicle_stock_number TEXT,
  preparation_notes TEXT,
  customer_notes TEXT,
  outcome TEXT,
  follow_up_actions TEXT,
  next_appointment_id TEXT,
  reminder_sent TEXT DEFAULT false,
  reminder_count TEXT DEFAULT 0,
  last_reminder_sent TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  completed_at TEXT,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled','confirmed','completed','cancelled','no_show')),
  scheduled_date TEXT,
  scheduled_time TEXT,
  notes TEXT,
  appointment_type TEXT DEFAULT 'appointment',
  FOREIGN KEY (customer_id) REFERENCES customers (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (lead_id) REFERENCES leads (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (assigned_sales_rep_id) REFERENCES sales_reps (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS communication_preference_log (

  id TEXT PRIMARY KEY,
  customer_id TEXT,
  changes TEXT NOT NULL,
  source TEXT DEFAULT 'customer_portal',
  ip_address TEXT,
  user_agent TEXT,
  session_id TEXT,
  notes TEXT,
  processed_by TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  action TEXT,
  FOREIGN KEY (customer_id) REFERENCES customers (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS customer_vehicle_interest (

  id TEXT PRIMARY KEY,
  customer_id TEXT,
  vehicle_id TEXT,
  notes TEXT,
  pros TEXT,
  cons TEXT,
  questions TEXT,
  budget_range TEXT,
  financing_preapproved TEXT DEFAULT false,
  trade_in_interest TEXT DEFAULT false,
  purchase_timeline TEXT,
  preferred_test_drive_dates TEXT,
  last_discussed TEXT,
  sales_rep_notes TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS customers (

  id TEXT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  phone_type TEXT DEFAULT 'mobile',
  address_line1 TEXT,
  address_line2 TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  country TEXT DEFAULT 'USA',
  customer_type TEXT DEFAULT 'prospect' CHECK (customer_type IN ('prospect', 'lead', 'active', 'inactive', 'vip')),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'archived', 'do_not_contact')),
  source TEXT DEFAULT 'website',
  preferred_vehicle_type TEXT,
  budget_min TEXT,
  budget_max TEXT,
  preferred_contact_method TEXT DEFAULT 'email' CHECK (preferred_contact_method IN ('email', 'phone', 'sms', 'mail')),
  assigned_sales_rep_id TEXT,
  assigned_sales_rep_name TEXT,
  lead_score TEXT DEFAULT 0,
  last_activity_date TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  email_consent TEXT DEFAULT false,
  sms_consent TEXT DEFAULT false,
  phone_consent TEXT DEFAULT false,
  gdpr_consent_date TEXT,
  do_not_contact_reason TEXT,
  normalized_email TEXT,
  normalized_phone TEXT,
  normalized_name TEXT,
  duplicate_count TEXT DEFAULT 0,
  merged_from TEXT DEFAULT '{}',
  merged_into TEXT,
  vehicle_interest TEXT,
  communication_preferences TEXT,
  consent_date TEXT,
  consent_source TEXT,
  gdpr_consent_withdrawn INTEGER DEFAULT 0,
  consent_withdrawn_date TEXT,
  consent_withdrawn_reason TEXT,
  preferences TEXT,
  FOREIGN KEY (assigned_sales_rep_id) REFERENCES sales_reps (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS email_templates (

  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  content TEXT NOT NULL,
  is_active TEXT DEFAULT true,
  variables TEXT DEFAULT '[]',
  usage_count TEXT DEFAULT 0,
  last_used TEXT,
  preview_text TEXT,
  test_email TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  template_type TEXT NOT NULL DEFAULT 'custom'
);

CREATE TABLE IF NOT EXISTS followup_analytics (

  id TEXT PRIMARY KEY,
  followup_id TEXT,
  customer_id TEXT,
  campaign_id TEXT,
  event_timestamp TEXT DEFAULT (datetime('now')),
  email_opened TEXT DEFAULT false,
  link_clicked TEXT,
  user_agent TEXT,
  ip_address TEXT,
  location_data TEXT,
  campaign_name TEXT,
  template_name TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  event_type TEXT NOT NULL,
  FOREIGN KEY (campaign_id) REFERENCES followup_campaigns (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (followup_id) REFERENCES followups (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS followup_campaigns (

  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  is_active TEXT DEFAULT true,
  priority TEXT DEFAULT 1,
  start_date TEXT,
  end_date TEXT,
  timezone TEXT DEFAULT 'America/New_York',
  total_sent TEXT DEFAULT 0,
  total_opened TEXT DEFAULT 0,
  total_clicked TEXT DEFAULT 0,
  total_converted TEXT DEFAULT 0,
  total_unsubscribed TEXT DEFAULT 0,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  target_audience TEXT DEFAULT 'all',
  campaign_type TEXT NOT NULL DEFAULT 'custom'
);

CREATE TABLE IF NOT EXISTS followup_rules (

  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  trigger_event TEXT NOT NULL,
  conditions TEXT DEFAULT '{}',
  customer_conditions TEXT DEFAULT '{}',
  lead_conditions TEXT DEFAULT '{}',
  interaction_conditions TEXT DEFAULT '{}',
  actions TEXT DEFAULT '[]',
  campaign_id TEXT,
  campaign_name TEXT,
  priority TEXT DEFAULT 1,
  delay_hours TEXT DEFAULT 0,
  is_active TEXT DEFAULT true,
  start_date TEXT,
  end_date TEXT,
  days_of_week TEXT,
  time_range_start TEXT,
  time_range_end TEXT,
  business_hours_only TEXT DEFAULT false,
  trigger_count TEXT DEFAULT 0,
  success_count TEXT DEFAULT 0,
  failure_count TEXT DEFAULT 0,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  email_template TEXT,
  sms_template TEXT,
  FOREIGN KEY (campaign_id) REFERENCES followup_campaigns (id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS followups (

  id TEXT PRIMARY KEY,
  customer_id TEXT,
  lead_id TEXT,
  campaign_id TEXT,
  rule_id TEXT,
  campaign_name TEXT,
  email TEXT DEFAULT false,
  sms TEXT DEFAULT false,
  email_template TEXT,
  sms_template TEXT,
  scheduled_date TEXT NOT NULL,
  sent_date TEXT,
  priority TEXT DEFAULT 1,
  skip_reason TEXT,
  error_message TEXT,
  email_consent TEXT DEFAULT false,
  sms_consent TEXT DEFAULT false,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled','sent','skipped','failed','cancelled')),
  FOREIGN KEY (campaign_id) REFERENCES followup_campaigns (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (lead_id) REFERENCES leads (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS interactions (

  id TEXT PRIMARY KEY,
  customer_id TEXT,
  lead_id TEXT,
  direction TEXT DEFAULT 'outbound' CHECK (direction IN ('inbound', 'outbound')),
  subject TEXT,
  content TEXT,
  summary TEXT,
  initiated_by TEXT,
  sales_rep_id TEXT,
  sales_rep_name TEXT,
  contact_method TEXT,
  contact_details TEXT,
  outcome TEXT,
  next_action TEXT,
  next_action_date TEXT,
  duration_minutes TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  description TEXT,
  notes TEXT,
  interaction_type TEXT DEFAULT 'note',
  FOREIGN KEY (customer_id) REFERENCES customers (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (lead_id) REFERENCES leads (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (sales_rep_id) REFERENCES sales_reps (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS leads (

  id TEXT PRIMARY KEY,
  customer_id TEXT,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  message TEXT,
  form_type TEXT DEFAULT 'general',
  lead_source TEXT DEFAULT 'website',
  page_url TEXT,
  vehicle_interest TEXT,
  vehicle_year TEXT,
  vehicle_make TEXT,
  vehicle_model TEXT,
  vehicle_trim TEXT,
  vehicle_stock_number TEXT,
  vehicle_price TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'qualified', 'converted', 'lost', 'duplicate')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  score TEXT DEFAULT 0,
  assigned_sales_rep_id TEXT,
  assigned_sales_rep_name TEXT,
  next_follow_up_date TEXT,
  follow_up_count TEXT DEFAULT 0,
  converted_to_customer TEXT DEFAULT false,
  conversion_date TEXT,
  conversion_value TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  last_contact TEXT DEFAULT (datetime('now')),
  normalized_email TEXT,
  normalized_phone TEXT,
  normalized_name TEXT,
  duplicate_count TEXT DEFAULT 0,
  merged_from TEXT DEFAULT '{}',
  merged_into TEXT,
  created_by TEXT DEFAULT 'system',
  sales_rep_notes TEXT,
  FOREIGN KEY (customer_id) REFERENCES customers (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (assigned_sales_rep_id) REFERENCES sales_reps (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS sales_reps (

  id TEXT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password_hash TEXT,
  employee_id TEXT UNIQUE,
  role TEXT DEFAULT 'sales_representative',
  department TEXT DEFAULT 'sales',
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'on_leave', 'terminated')),
  permissions TEXT DEFAULT 'view_customers,manage_leads',
  hire_date TEXT,
  current_lead_count TEXT DEFAULT 0,
  current_customer_count TEXT DEFAULT 0,
  monthly_sales_target TEXT,
  specializations TEXT,
  languages TEXT DEFAULT 'english',
  preferred_contact_method TEXT DEFAULT 'email',
  working_hours TEXT DEFAULT '{"monday": {"start": "09:00", "end": "18:00"}, "tuesday": {"start": "09:00", "end": "18:00"}, "wednesday": {"start": "09:00", "end": "18:00"}, "thursday": {"start": "09:00", "end": "18:00"}, "friday": {"start": "09:00", "end": "18:00"}, "saturday": {"start": "09:00", "end": "17:00"}, "sunday": null}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  last_login TEXT,
  created_by TEXT,
  updated_by TEXT,
  name TEXT,
  position TEXT,
  image TEXT,
  capacity INTEGER DEFAULT 0,
  territory TEXT,
  source_expertise TEXT,
  budget_expertise TEXT
);

CREATE TABLE IF NOT EXISTS sms_templates (

  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  is_active TEXT DEFAULT true,
  character_count TEXT,
  variables TEXT DEFAULT '[]',
  usage_count TEXT DEFAULT 0,
  last_used TEXT,
  test_phone TEXT,
  tags TEXT,
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  template_type TEXT NOT NULL DEFAULT 'custom'
);

CREATE TABLE IF NOT EXISTS tasks (

  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  assigned_to TEXT,
  assigned_to_name TEXT,
  customer_id TEXT,
  lead_id TEXT,
  appointment_id TEXT,
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  due_date TEXT,
  completed_date TEXT,
  estimated_duration_minutes TEXT,
  actual_duration_minutes TEXT,
  tags TEXT,
  checklist TEXT DEFAULT '[]',
  attachments TEXT,
  outcome TEXT,
  lessons_learned TEXT,
  is_recurring TEXT DEFAULT false,
  recurrence_pattern TEXT,
  next_occurrence TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  created_by TEXT,
  updated_by TEXT,
  task_type TEXT DEFAULT 'follow_up',
  status TEXT DEFAULT 'open' CHECK (status IN ('open','in_progress','blocked','completed','cancelled')),
  FOREIGN KEY (customer_id) REFERENCES customers (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (lead_id) REFERENCES leads (id)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (assigned_to) REFERENCES sales_reps (id)
    ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS vehicles (

  id TEXT PRIMARY KEY,
  stock_number TEXT UNIQUE NOT NULL,
  vin TEXT UNIQUE,
  year TEXT NOT NULL,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  trim TEXT,
  body_style TEXT,
  exterior_color TEXT,
  interior_color TEXT,
  engine TEXT,
  transmission TEXT,
  drivetrain TEXT,
  fuel_type TEXT,
  mileage TEXT,
  list_price TEXT,
  sale_price TEXT,
  msrp TEXT,
  features TEXT,
  packages TEXT,
  image_urls TEXT,
  video_url TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  date_in_stock TEXT,
  date_sold TEXT,
  status TEXT DEFAULT 'available',
  created_by TEXT DEFAULT 'system'
);


-- ---------------------------------------------------------------------
-- Search
--
-- These six are named by the code and were in neither the Postgres source nor
-- the generated schema, so every read and write against them failed with
-- "no such table". They are the searchable projection of the four tables the
-- staff actually search.
--
-- Keyed on the source row's own id rather than a generated one: the index row
-- and the source row share an identity, which is what makes the CASCADE below
-- correct. There is no separate primary key to keep in step.
--
-- `searchable_text` is a lowercased concatenation of the fields a person would
-- type, so LIKE '%...%' can use the index prefix and search stays one query
-- instead of a join per field.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS customer_search_index (
  customer_id    TEXT PRIMARY KEY,
  search_vector  TEXT,
  searchable_text TEXT NOT NULL,
  last_updated   TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lead_search_index (
  lead_id        TEXT PRIMARY KEY,
  search_vector  TEXT,
  searchable_text TEXT NOT NULL,
  last_updated   TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS interaction_search_index (
  interaction_id TEXT PRIMARY KEY,
  search_vector  TEXT,
  searchable_text TEXT NOT NULL,
  last_updated   TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (interaction_id) REFERENCES interactions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vehicle_search_index (
  vehicle_id     TEXT PRIMARY KEY,
  search_vector  TEXT,
  searchable_text TEXT NOT NULL,
  last_updated   TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
);

-- One row per index, not per document. Keyed by the index name so a rebuild can
-- be in progress for one index without the others being marked stale.
CREATE TABLE IF NOT EXISTS search_index_metadata (
  index_type     TEXT PRIMARY KEY,
  last_build_time TEXT,
  duration_ms    INTEGER,
  record_count   INTEGER DEFAULT 0,
  status         TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'building', 'ready', 'failed')),
  metadata       TEXT
);

-- A staff member's saved search. `user_id` is a Netlify Identity `sub`, which is
-- the same value `sales_reps.id` is keyed on (see utils/staff-profile.js), so
-- the reference holds and survives an Identity re-invite.
CREATE TABLE IF NOT EXISTS saved_searches (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL,
  name          TEXT NOT NULL,
  query         TEXT NOT NULL,
  filters       TEXT,
  entity_types  TEXT,
  created_by    TEXT,
  created_at    TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES sales_reps (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_saved_searches_user ON saved_searches (user_id, name);

-- ---------------------------------------------------------------------
-- Replacing Netlify Blobs
--
-- Three features were written against Blobs:
--
--   google-calendar   one shared OAuth token under the key `token`
--   booking-queue     one key per request
--   vehicle-features  one key, `favourites`
--
-- None of them work on this site, and the reason is not a bug in any of the
-- three: a Netlify function cannot reach a Blobs store without an explicit
-- siteID and token, and this account's plan refuses to issue one. The functions
-- all report their own absence honestly rather than failing silently, which is
-- why this was not noticed -- but bookings are emailed and not recorded,
-- favourites do not persist, and the calendar cannot connect.
--
-- These three tables are the replacement. The database is the one piece of
-- infrastructure on this site that is confirmed working, and moving to it makes
-- the storage per-user and transactional rather than a single shared key.
-- ---------------------------------------------------------------------

-- One Google Calendar connection per staff member.
--
-- `user_id` is the Netlify Identity `sub`, which is the same value
-- `sales_reps.id` is keyed on (see utils/staff-profile.js), so the foreign key
-- holds and survives an Identity re-invite.
--
-- ONE ROW PER PERSON, which is the whole point. The old design had a single
-- token under one key, so the first person to connect owned the dealership's
-- calendar and everybody else silently shared it -- bookings landed in whoever
-- connected first, and one person disconnecting removed it for all of them.
--
-- The refresh token is a long-lived credential. It is stored here and nowhere
-- else, and `ON DELETE CASCADE` from sales_reps means it goes when the person
-- does -- revocation is a delete, which is what makes withdrawing consent
-- actually take effect.
CREATE TABLE IF NOT EXISTS google_calendar_tokens (
  user_id         TEXT PRIMARY KEY,
  access_token    TEXT,
  refresh_token   TEXT,
  expires_at      INTEGER,
  scope           TEXT,
  google_email    TEXT,
  calendar_id     TEXT DEFAULT 'primary',
  connected_at    TEXT,
  updated_at      TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES sales_reps (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_google_tokens_expiry ON google_calendar_tokens (expires_at);

-- ---------------------------------------------------------------------
-- Site settings
--
-- WHY THIS TABLE EXISTS
-- ---------------------
-- The Decap CMS cannot be used for anything that has to change NOW. It commits
-- to git, and this site deploys PREBUILT from the CI host (netlify.toml sets
-- [build] command = ""), so a save produces a commit and no build: the change
-- stays unpublished until someone runs a build. An editor pressing Save and
-- seeing "Saved" is the failure mode, not a feature -- see docs/ADMIN.md.
--
-- So the copy an admin actually needs to change during business hours lives
-- here, and the front end reads it at request time. The build stays prebuilt and
-- costs no Netlify build minutes.
--
-- WHAT IS AND IS NOT IN HERE
-- --------------------------
-- Chrome and settings only: the signage copy, the stock-alert pitch, the
-- contact chips, an emergency banner.
--
-- NOT page content. Inventory and specials are the pages search traffic lands
-- on, and a value injected by JavaScript is invisible to a crawler, so those
-- must be in the served HTML. Moving them here would trade a working search
-- presence for convenience. They need a build, and the build is the honest
-- answer for them.
--
-- One row per key rather than one document holding an object, for the same
-- reason vehicle_favourites is one row per vehicle: a document is a
-- read-modify-write on every edit, so two people changing two different values
-- at the same moment lose one of the two. Rows do not collide.
--
-- `is_public` decides who may read it. Settings the public front end fetches
-- are public; anything internal is not, and is refused without a session rather
-- than filtered out client-side.
CREATE TABLE IF NOT EXISTS site_settings (
  key         TEXT PRIMARY KEY,
  value       TEXT,
  -- 'text' | 'textarea' | 'boolean' | 'url' | 'phone'
  -- The admin form is built from this, so a setting cannot need a form change
  -- to be edited, and a textarea cannot be silently truncated to a line.
  kind        TEXT NOT NULL DEFAULT 'text'
              CHECK (kind IN ('text','textarea','boolean','url','phone')),
  label       TEXT,
  -- Which page the value appears on, so the form can be grouped and so a
  -- reader knows where to look. 'global' means footer/header chrome.
  applies_to  TEXT NOT NULL DEFAULT 'global',
  -- False for internal notes; never served to the public front end.
  is_public   INTEGER NOT NULL DEFAULT 1 CHECK (is_public IN (0, 1)),
  -- Set when a value has deliberately been blanked, so "not set" and
  -- "somebody typed a space" are different states.
  is_blank    INTEGER NOT NULL DEFAULT 0 CHECK (is_blank IN (0, 1)),
  updated_by  TEXT,
  updated_at  TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (updated_by) REFERENCES sales_reps (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_site_settings_applies ON site_settings (applies_to);
CREATE INDEX IF NOT EXISTS idx_site_settings_public ON site_settings (is_public, key);

-- A test-drive request waiting to go on a calendar.
--
-- Blobs stored these as `req-<id>` JSON documents. A table is the right shape:
-- the pending queue is a filtered view, and `WHERE status = 'new'` over rows is
-- something the database can answer with an index rather than something the
-- application has to enumerate keys to find.
--
-- `status` is the queue position: new -> synced, or -> sync-failed, or ->
-- cancelled. An index on (status, preferred_date) makes "what is waiting, soonest
-- first" the shape the query planner wants.
CREATE TABLE IF NOT EXISTS booking_requests (
  id               TEXT PRIMARY KEY,
  status           TEXT NOT NULL DEFAULT 'new'
                   CHECK (status IN ('new','synced','sync-failed','cancelled')),
  vehicle_id       TEXT,
  vehicle_title    TEXT,
  full_name        TEXT,
  email            TEXT,
  phone            TEXT,
  preferred_date   TEXT,
  preferred_time   TEXT,
  comments         TEXT,
  created_at       TEXT DEFAULT (datetime('now')),
  updated_at       TEXT,
  recorded_at      TEXT,
  google_event_id  TEXT,
  google_event_link TEXT,
  synced_at        TEXT,
  sync_error       TEXT
);
CREATE INDEX IF NOT EXISTS idx_bookings_pending ON booking_requests (status, preferred_date);
CREATE INDEX IF NOT EXISTS idx_bookings_email  ON booking_requests (email);

-- Which vehicles are featured on the site.
--
-- One row per vehicle rather than one document holding a list of slugs. A list in
-- a single JSON blob means every read rewrites the whole document and two people
-- starring different vehicles at the same moment loses one of the two. A row per
-- vehicle makes the read a SELECT and the write an INSERT, and they do not
-- collide.
CREATE TABLE IF NOT EXISTS vehicle_favourites (
  slug         TEXT PRIMARY KEY,
  featured     INTEGER NOT NULL DEFAULT 1,
  updated_at   TEXT DEFAULT (datetime('now'))
);

-- How this site sends mail. One row (id = 1), edited at /admin/email.
--
-- NOT site_settings. That table's GET publishes every `is_public = 1` row to
-- ANONYMOUS callers, on purpose, because the front end has no session. An SMTP
-- password stored there would be served to the internet by a query the schema
-- itself describes as safe. There is no public read path to this table at all.
--
-- `smtp_pass` NULL means "the secret lives in the Netlify UI instead", which is
-- a real state rather than an empty password. utils/mail-config.js falls back
-- to process.env in that case, so either place works.
--
-- `enabled = 0` stops every send without deleting the credentials, so a
-- half-entered provider cannot start sending by being finished by accident.
-- Who changed what, and when. Added 2026-10-01.
--
-- Deliberately NOT cascaded from `customers` or `leads`. An audit table that
-- empties itself when the subject is erased is useless precisely when it is
-- most needed, and `actor_id` is SET NULL so an audit row outlives the staff
-- member who wrote it.
--
-- Deliberately does NOT store a customer's identifying fields. `rows_affected`
-- on an erasure is the evidence that data was removed; retaining the removed
-- data "for the audit trail" would make the erasure incomplete. See
-- database/turso/005_audit_log.sql.
CREATE TABLE IF NOT EXISTS audit_log (
  id            TEXT PRIMARY KEY,
  actor_id      TEXT,
  actor_email   TEXT,
  actor_role    TEXT,
  action        TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT,
  reason        TEXT,
  detail        TEXT,
  rows_affected INTEGER NOT NULL DEFAULT 0,
  ip            TEXT,
  user_agent    TEXT,
  created_at    TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (actor_id) REFERENCES sales_reps (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity  ON audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_log (actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action  ON audit_log (action, created_at DESC);

CREATE TABLE IF NOT EXISTS mail_config (
  id           INTEGER PRIMARY KEY CHECK (id = 1),
  provider     TEXT NOT NULL DEFAULT 'custom'
               CHECK (provider IN ('sendgrid','mailgun','resend','postmark','custom')),
  smtp_host    TEXT,
  smtp_port    INTEGER NOT NULL DEFAULT 587,
  smtp_secure  INTEGER NOT NULL DEFAULT 0 CHECK (smtp_secure IN (0, 1)),
  smtp_user    TEXT,
  smtp_pass    TEXT,
  email_from   TEXT,
  enabled      INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  updated_by   TEXT,
  updated_at   TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (updated_by) REFERENCES sales_reps (id) ON DELETE SET NULL
);

-- Indexes

-- Foreign keys
CREATE INDEX IF NOT EXISTS idx_customers_rep          ON customers (assigned_sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_leads_customer          ON leads (customer_id);
CREATE INDEX IF NOT EXISTS idx_leads_rep               ON leads (assigned_sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_interactions_customer   ON interactions (customer_id);
CREATE INDEX IF NOT EXISTS idx_interactions_lead       ON interactions (lead_id);
CREATE INDEX IF NOT EXISTS idx_interactions_rep        ON interactions (sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_appointments_customer   ON appointments (customer_id);
CREATE INDEX IF NOT EXISTS idx_appointments_lead       ON appointments (lead_id);
CREATE INDEX IF NOT EXISTS idx_appointments_rep        ON appointments (assigned_sales_rep_id);
CREATE INDEX IF NOT EXISTS idx_tasks_customer          ON tasks (customer_id);
CREATE INDEX IF NOT EXISTS idx_tasks_lead              ON tasks (lead_id);
CREATE INDEX IF NOT EXISTS idx_tasks_rep               ON tasks (assigned_to);
CREATE INDEX IF NOT EXISTS idx_rules_campaign          ON followup_rules (campaign_id);
CREATE INDEX IF NOT EXISTS idx_followups_campaign      ON followups (campaign_id);
CREATE INDEX IF NOT EXISTS idx_followups_customer      ON followups (customer_id);
CREATE INDEX IF NOT EXISTS idx_followups_lead          ON followups (lead_id);
CREATE INDEX IF NOT EXISTS idx_analytics_campaign      ON followup_analytics (campaign_id);
CREATE INDEX IF NOT EXISTS idx_analytics_followup      ON followup_analytics (followup_id);
CREATE INDEX IF NOT EXISTS idx_prefs_customer          ON communication_preference_log (customer_id);

-- Filter and sort columns the queries actually use
CREATE INDEX IF NOT EXISTS idx_customers_status        ON customers (status);
CREATE INDEX IF NOT EXISTS idx_customers_created       ON customers (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_status            ON leads (status);
CREATE INDEX IF NOT EXISTS idx_leads_created           ON leads (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_email             ON leads (email);
CREATE INDEX IF NOT EXISTS idx_interactions_recent     ON interactions (customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_interactions_rep_recent ON interactions (sales_rep_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_recent     ON appointments (customer_id, scheduled_start DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_upcoming   ON appointments (assigned_sales_rep_id, scheduled_start DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_status     ON appointments (status, scheduled_start);
CREATE INDEX IF NOT EXISTS idx_appointments_start      ON appointments (scheduled_start);
CREATE INDEX IF NOT EXISTS idx_tasks_open              ON tasks (assigned_to, status);
CREATE INDEX IF NOT EXISTS idx_tasks_due               ON tasks (status, due_date);
CREATE INDEX IF NOT EXISTS idx_vehicles_available     ON vehicles (status);
CREATE INDEX IF NOT EXISTS idx_vehicles_make_model     ON vehicles (make, model);
CREATE INDEX IF NOT EXISTS idx_vehicles_price          ON vehicles (list_price);
CREATE INDEX IF NOT EXISTS idx_vehicles_stock          ON vehicles (stock_number);
CREATE INDEX IF NOT EXISTS idx_followups_due           ON followups (status, scheduled_date);
CREATE INDEX IF NOT EXISTS idx_followups_recent        ON followups (customer_id, scheduled_date DESC);
CREATE INDEX IF NOT EXISTS idx_rules_active            ON followup_rules (trigger_event, is_active);
CREATE INDEX IF NOT EXISTS idx_campaigns_active        ON followup_campaigns (is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_events        ON followup_analytics (campaign_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reps_email              ON sales_reps (email);
CREATE INDEX IF NOT EXISTS idx_reps_status             ON sales_reps (status);
CREATE INDEX IF NOT EXISTS idx_search_customers        ON customer_search_index (searchable_text);
CREATE INDEX IF NOT EXISTS idx_search_leads            ON lead_search_index (searchable_text);
CREATE INDEX IF NOT EXISTS idx_search_vehicles         ON vehicle_search_index (searchable_text);


-- ---------------------------------------------------------------------
-- Views
--
-- The joins this application performs over and over, written once.
--
-- Every one of these was duplicated across functions, which means every one of
-- them could be, and was, subtly different. customer-dashboard, sales-customers
-- and followup-system each assembled a customer-plus-rep shape of their own.
--
-- A view is the join stated once. The functions select from it, the dashboard
-- aggregates from it, and a fix to the join is a fix to all of them at the same
-- time -- which is the difference between one bug and three.
-- ---------------------------------------------------------------------

-- A customer with the rep who owns them. LEFT JOIN, not INNER: a customer with
-- no assigned rep is still a customer, and an inner join silently loses them.
CREATE VIEW IF NOT EXISTS v_customer_with_rep AS
SELECT
  c.id,
  c.first_name,
  c.last_name,
  c.email,
  c.phone,
  c.status,
  c.customer_type,
  c.assigned_sales_rep_id,
  r.first_name AS rep_first_name,
  r.last_name  AS rep_last_name,
  r.email      AS rep_email,
  r.phone      AS rep_phone,
  r.role       AS rep_role
FROM customers c
LEFT JOIN sales_reps r ON r.id = c.assigned_sales_rep_id;

-- A customer with the counts an operator actually asks for. Doing this with
-- correlated subqueries per customer is what the dashboard did, and it is one
-- query per customer per count.
CREATE VIEW IF NOT EXISTS v_customer_summary AS
SELECT
  c.id,
  c.first_name,
  c.last_name,
  c.email,
  c.phone,
  c.status,
  c.customer_type,
  c.assigned_sales_rep_id,
  c.created_at,
  (SELECT COUNT(*) FROM appointments a
     WHERE a.customer_id = c.id)                        AS appointment_count,
  (SELECT COUNT(*) FROM interactions i
     WHERE i.customer_id = c.id)                        AS interaction_count,
  (SELECT COUNT(*) FROM leads l
     WHERE l.customer_id = c.id)                         AS lead_count,
  (SELECT COUNT(*) FROM tasks t
     WHERE t.customer_id = c.id AND t.status != 'completed') AS open_task_count,
  (SELECT MAX(a.scheduled_start) FROM appointments a
     WHERE a.customer_id = c.id)                        AS last_appointment
FROM customers c;

-- Inventory that is actually sellable. The status filter lives here rather than
-- in a dozen queries that each remember it slightly differently -- and the
-- column this filters on did not exist until 003, so every one of those queries
-- was failing.
CREATE VIEW IF NOT EXISTS v_available_inventory AS
SELECT
  v.id,
  v.stock_number,
  v.vin,
  v.year,
  v.make,
  v.model,
  v.trim,
  v.body_style,
  v.exterior_color,
  v.interior_color,
  v.mileage,
  v.list_price,
  v.status,
  v.image_urls
FROM vehicles v
WHERE v.status = 'available';

-- The sales pipeline, one row per lead, with the customer it became. Leads are
-- the intake record and customers are what they turn into, and the join between
-- the two is the question the dashboard exists to answer.
CREATE VIEW IF NOT EXISTS v_sales_pipeline AS
SELECT
  l.id                AS lead_id,
  l.first_name,
  l.last_name,
  l.email,
  l.phone,
  l.status,
  l.form_type,
  l.lead_source,
  l.vehicle_interest,
  l.assigned_sales_rep_id,
  l.created_at,
  c.id                AS customer_id,
  c.status            AS customer_status,
  r.first_name        AS rep_first_name,
  r.last_name         AS rep_last_name
FROM leads l
LEFT JOIN customers c ON c.id = l.customer_id
LEFT JOIN sales_reps r ON r.id = l.assigned_sales_rep_id;

-- A rep's diary: what is booked, for whom. One row per appointment, with the
-- customer joined in, which is what the calendar and the rep dashboard both
-- need and both used to assemble themselves.
CREATE VIEW IF NOT EXISTS v_rep_schedule AS
SELECT
  a.id,
  a.appointment_type,
  a.title,
  a.scheduled_start,
  a.scheduled_end,
  a.status,
  a.assigned_sales_rep_id,
  a.vehicle_of_interest,
  c.id        AS customer_id,
  c.first_name AS customer_first_name,
  c.last_name  AS customer_last_name,
  c.phone      AS customer_phone,
  c.email      AS customer_email
FROM appointments a
LEFT JOIN customers c ON c.id = a.customer_id;

-- Campaign performance, aggregated once. Every report that needed these numbers
-- wrote its own SUM/CASE block, and the definitions drifted.
CREATE VIEW IF NOT EXISTS v_campaign_performance AS
SELECT
  fc.id AS campaign_id,
  fc.name,
  fc.campaign_type,
  fc.is_active,
  fc.created_at,
  COUNT(DISTINCT f.id)   AS followup_count,
  COUNT(DISTINCT r.id)   AS rule_count,
  COUNT(DISTINCT a.id)   AS analytics_event_count
FROM followup_campaigns fc
LEFT JOIN followups f          ON f.campaign_id = fc.id
LEFT JOIN followup_rules r     ON r.campaign_id = fc.id
LEFT JOIN followup_analytics a ON a.campaign_id = fc.id
GROUP BY fc.id;
