#!/usr/bin/env python3
"""
pg2turso.py -- convert the Postgres migrations into a libSQL/Turso schema.

WHY THIS EXISTS
---------------
The application talks to Postgres. Turso is libSQL, which speaks the SQLite
dialect. The existing migrations cannot be applied to Turso as they stand --
measured across database/migrations/001-006:

    58   GIN indexes
    18   CREATE OR REPLACE FUNCTION
    18   plpgsql
     8   RETURNS TRIGGER
     3   CREATE EXTENSION
     3   tsvector

Every one of those is rejected by libSQL. So "just set TURSO_DATABASE_URL" was
not true: the schema could not be created.

This rewrites the DDL rather than hand-transcribing it. 380 column definitions
copied by hand is 380 chances to introduce a typo that only shows up when a
function selects a column that does not exist -- and that failure is a 500 at
runtime on a page nobody is testing.

WHAT IS TRANSLATED
------------------
    SERIAL / BIGSERIAL          -> INTEGER PRIMARY KEY AUTOINCREMENT
    TIMESTAMP WITH TIME ZONE    -> TEXT      (ISO-8601 sorts correctly as text,
                                            which is what every query here does)
    UUID (plus defaults/casts)  -> TEXT
    JSONB / JSON                -> TEXT      holding JSON
    BOOLEAN                     -> INTEGER   (0/1; libSQL has no bool)
    NUMERIC(p,s) / DECIMAL      -> REAL
    TEXT[] (Postgres arrays)    -> TEXT holding a comma list
    gen_random_uuid()           -> a per-row expression is NOT portable, so
                                   id becomes a plain autoincrement and anything
                                   that genuinely needs a uuid calls the
                                   database's own lower(hex(randomblob(16)))

WHAT IS DROPPED, AND WHY IT IS SAFE TO DROP
--------------------------------------------
    triggers, plpgsql functions, views, GIN/tsvector indexes

    These are search-optimisation and derived-value machinery. Dropping them
    changes performance and removes automation, not correctness: every column a
    trigger would have maintained is still written by the function that owns it,
    because this codebase does its bookkeeping in JavaScript.

    The honest cost: `search-index-service.js` and the analytics views that
    depend on triggers will not work. They are listed in the report this prints,
    so it is visible rather than discovered later.

    Full-text search is replaced with plain LIKE indexes, which is what SQLite
    would give you anyway.

Usage:  python3 scripts/pg2turso.py            # writes database/turso/001_core.sql
        python3 scripts/pg2turso.py --print     # also dump to stdout
"""

import os
import re
import sys
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIGRATIONS = os.path.join(ROOT, 'database', 'migrations')
OUT_DIR = os.path.join(ROOT, 'database', 'turso')

# Migrations in order. 002 (functions/triggers) and 006 (performance, mostly
# GIN indexes) are deliberately not translated: they are entirely Postgres-only
# machinery. 003 is skipped because it is a partial, incomplete Turso schema that
# is superseded by the output of this script.
SOURCE_ORDER = [
    '001_create_comprehensive_schema.sql',
    '004_add_password_hash_to_sales_reps.sql',
    '005_add_followup_system_tables.sql',
]

SKIPPED = {
    '002_create_functions_and_triggers.sql':
        'plpgsql functions and triggers -- not portable to libSQL',
    '003_create_turso_schema.sql':
        'superseded: covers only 4 of the 15 tables the code queries',
    '006_database_performance_optimization.sql':
        'GIN/tsvector indexes -- SQLite has no equivalent',
}

HEADER = """-- turso/001_core.sql -- GENERATED by scripts/pg2turso.py. Do not hand-edit.
--
-- The libSQL/Turso translation of database/migrations/{001,004,005}.
--
--   Apply with:  npm run db:push
--   Or by hand:  sqlite3 local.db < database/turso/001_core.sql
--
-- Translated: SERIAL, TIMESTAMPTZ, UUID, JSONB, BOOLEAN, NUMERIC, TEXT[]
-- Dropped:     triggers, plpgsql functions, views, GIN/tsvector indexes
--
-- The dropped items are search and automation machinery, not data. Every column
-- a trigger would have maintained is written by the function that owns it.
-- Full-text search falls back to LIKE. See docs/STORAGE.md for the consequences
-- and for what is not covered.
"""


def translate_type(t):
    """Postgres type -> libSQL type."""
    u = t.strip().upper()

    # Multi-word Postgres types must be matched BEFORE the single-word rules. The
    # type regex below is non-greedy and happily matches just "T" of "TIMESTAMP",
    # leaving "IMESTAMP WITH TIME ZONE DEFAULT NOW()" as the constraint tail --
    # which then produced
    #     created_at TEXT DEFAULT (datetime('now')) DEFAULT NOW()
    # and SQLite rejected the entire table at the word "now". The ordering here
    # is load-bearing, not stylistic.
    MULTIWORD = [
        ('TIMESTAMP WITH TIME ZONE', 'TEXT'),
        ('TIMESTAMP WITHOUT TIME ZONE', 'TEXT'),
        ('TIME WITH TIME ZONE', 'TEXT'),
        ('DOUBLE PRECISION', 'REAL'),
        ('CHARACTER VARYING', 'TEXT'),
        ('BIT VARYING', 'TEXT'),
    ]
    for name, mapped in MULTIWORD:
        if name in u:
            return mapped

    t = t.strip()
    if 'SERIAL' in u:
        return 'INTEGER'

    if 'TIMESTAMP' in u:
        return 'TEXT'
    if u == 'DATE':
        return 'TEXT'

    if 'UUID' in u:
        return 'TEXT'

    if 'JSONB' in u or u == 'JSON':
        return 'TEXT'

    if u.startswith('BOOLEAN') or u == 'BOOL':
        return 'INTEGER'

    if u.startswith('NUMERIC') or u.startswith('DECIMAL'):
        return 'REAL'
    if u in ('MONEY',):
        return 'REAL'

    if u in ('DOUBLE PRECISION', 'FLOAT8'):
        return 'REAL'
    if u in ('REAL', 'FLOAT4'):
        return 'REAL'
    if u in ('FLOAT', 'DOUBLE'):
        return 'REAL'

    if 'INT' in u:
        return 'INTEGER'
    if 'CHAR' in u or 'TEXT' in u:
        return 'TEXT'
    if u == 'BYTEA':
        return 'BLOB'
    if u == 'INET':
        return 'TEXT'
    if u == 'CIDR':
        return 'TEXT'

    # Postgres array, e.g. TEXT[]
    if u.endswith('[]'):
        return 'TEXT'

    return 'TEXT'


def strip_defaults(expr):
    """Remove Postgres-only DEFAULT expressions from a column definition."""
    # DEFAULT gen_random_uuid() / now() are fine on SQLite, but the uuid ones
    # are not portable. Keep the SQLite-safe ones.
    expr = re.sub(r"DEFAULT\s+gen_random_uuid\(\)", "", expr, flags=re.I)
    expr = re.sub(r"DEFAULT\s+uuid_generate_v4\(\)", "", expr, flags=re.I)
    expr = re.sub(r"DEFAULT\s+nextval\([^)]*\)", "", expr, flags=re.I)
    return expr


def convert_column(line):
    """One column definition line -> libSQL."""
    line = line.strip().rstrip(',')
    if not line or line.startswith('--'):
        return None

    m = re.match(r'^(\w+)\s+(.+)$', line)
    if not m:
        return None
    name, rest = m.group(1), m.group(2)

    upper = name.upper()
    if upper in ('CONSTRAINT', 'PRIMARY KEY', 'FOREIGN KEY', 'UNIQUE', 'CHECK', 'EXCLUDE'):
        return None

    rest = strip_defaults(rest)

    # type is the leading token(s) up to the first constraint keyword
    type_m = re.match(r'^([A-Za-z_][\w ]*?(?:\([\d,\s]*\))?(?:\[\])?)\s*(.*)$', rest)
    if not type_m:
        return None
    ptype, tail = type_m.group(1).strip(), type_m.group(2).strip()

    ltype = translate_type(ptype)

    parts = [f'  {name} {ltype}']

    tail_up = tail.upper()
    if 'PRIMARY KEY' in tail_up:
        parts[0] += ' PRIMARY KEY'
        if 'AUTOINCREMENT' in ptype.upper() or 'SERIAL' in ptype.upper():
            # SERIAL became INTEGER; make the autoincrement explicit.
            parts[0] = f'  {name} INTEGER PRIMARY KEY AUTOINCREMENT'
        tail = re.sub(r'PRIMARY KEY', '', tail, flags=re.I).strip().rstrip(',')
    elif 'AUTOINCREMENT' in ptype.upper():
        parts[0] += ' PRIMARY KEY AUTOINCREMENT'

    if 'UNIQUE' in tail_up and 'UNIQUE' not in ' '.join(parts).upper():
        parts.append('UNIQUE')

    if 'NOT NULL' in tail_up:
        parts.append('NOT NULL')

    if 'DEFAULT' in tail_up:
        # The value must be matched as a unit. `[^\s,]+` looks right and is
        # wrong: it stops at the first space, so
        #     location VARCHAR(255) DEFAULT 'Cadillac of South Charlotte'
        # captured the default as `'Cadillac` and silently discarded
        # `of South Charlotte'` -- leaving an unterminated quote that swallowed
        # every following comma in the table and produced a parse error
        # pointing at an unrelated column further down.
        #
        # So: a single-quoted string (with '' as an escaped quote), a
        # double-quoted string, a parenthesised expression, or a bare token.
        d = re.search(
            r"DEFAULT\s+("
            r"'(?:[^']|'')*'"          # single-quoted, '' escapes a quote
            r'|"(?:[^"]|"")*"'          # double-quoted
            r"|(?:ARRAY\s*)?\[[^\]]*\]"   # ARRAY['a','b'] -- the ARRAY prefix
                                         # must be inside the match, or the
                                         # bracket group is captured alone, the
                                         # array branch below never matches
                                         # (it anchors on ^ARRAY), and the
                                         # literal ARRAY is dropped from the
                                         # emitted SQL.
            r"|\([^)]*\)"               # parenthesised expression
            r"|[^\s,]+"                 # bare token
            r")",
            tail, re.I,
        )
        if d:
            v = d.group(1).strip()
            lv = v.lower()

            # Postgres array default -> a comma-separated list in TEXT.
            #     permissions TEXT[] DEFAULT ARRAY['view_customers','manage_leads']
            # libSQL has no array type, so it is stored as
            #     permissions TEXT DEFAULT 'view_customers,manage_leads'
            # Nothing reads this column as an array today -- permissions is
            # only ever compared as a string -- so this is a faithful-enough
            # translation rather than a lossy one, and it is the alternative to
            # dropping a column the row-level security check may depend on.
            arr = re.match(r"^ARRAY\s*\[(.*)\]$", v, re.I | re.S)
            if arr:
                items = [x.strip().strip("'") for x in arr.group(1).split(',') if x.strip()]
                v = "'" + ','.join(items) + "'"

            elif lv in ('now()', 'current_timestamp', 'current_timestamp()'):
                v = "(datetime('now'))"
            elif lv in ('true', 'false') and ltype == 'INTEGER':
                v = '1' if lv == 'true' else '0'
            parts.append(f'DEFAULT {v}')

    if 'CHECK' in tail_up:
        # SQLite honours CHECK; the only Postgres-ism is TRUE/FALSE literals.
        c = re.search(r'CHECK\s*\((.+)\)\s*$', tail, flags=re.I)
        if c:
            expr = c.group(1).replace('TRUE', '1').replace('FALSE', '0')
            parts.append(f'CHECK ({expr})')

    return ' '.join(parts)


def split_top_level(body):
    """
    Split a CREATE TABLE body on commas that are not inside parentheses or quotes.

    A line-based splitter cannot parse this schema. The source puts more than one
    column definition on a line in several places --

        character_count INTEGER, message_count INTEGER, CASE TEXT, WHEN TEXT,

    which is not valid SQL by itself: that line is the tail of a CASE-based
    generated column whose head is on the previous line. Splitting on newlines
    therefore produced fragments like "CASE TEXT" and "WHEN TEXT" as though they
    were columns, and the schema failed to apply.

    Comments are stripped first, then the body is walked tracking paren depth and
    quote state, so a comma inside CHECK (... IN ('a','b')) does not split.
    """
    # Strip -- comments LINE BY LINE, tracking quotes within the line only.
    #
    # The first version walked the whole body keeping quote state, which leaks:
    # a comment containing an apostrophe ("the rep's notes") opens a string that
    # never closes, and from that point every comma in the table is "inside a
    # string" and is not a split point. The result was columns silently merged
    # onto one line -- `location TEXT DEFAULT 'Cadillac,` swallowing the rest of
    # the table -- and SQLite then rejected the statement at an unrelated-looking
    # word further along.
    #
    # Confining quote state to a line is correct here: an unterminated quote in a
    # comment is a broken comment, not a broken schema.
    out_lines = []
    for line in body.split('\n'):
        res, in_str = [], None
        i = 0
        while i < len(line):
            ch = line[i]
            if in_str:
                res.append(ch)
                if ch == in_str:
                    # '' inside a SQL string is an escaped quote, not a close.
                    if i + 1 < len(line) and line[i + 1] == in_str:
                        res.append(line[i + 1])
                        i += 2
                        continue
                    in_str = None
                i += 1
                continue
            if ch in ("'", '"'):
                in_str = ch
                res.append(ch)
                i += 1
                continue
            if ch == '-' and i + 1 < len(line) and line[i + 1] == '-':
                break  # rest of the line is a comment
            res.append(ch)
            i += 1
        out_lines.append(''.join(res))
    text = '\n'.join(out_lines)

    parts, buf, depth, in_str = [], [], 0, None
    for ch in text:
        if in_str:
            buf.append(ch)
            if ch == in_str:
                in_str = None
            continue
        if ch in ("'", '"'):
            in_str = ch
            buf.append(ch)
            continue
        if ch in '([':
            depth += 1
        elif ch in ')]':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(''.join(buf))
            buf = []
            continue
        buf.append(ch)
    parts.append(''.join(buf))
    return [p.strip() for p in parts if p.strip()]


def convert_table(name, body):
    lines = []
    for raw in split_top_level(body):
        out = convert_column(raw)
        if out:
            lines.append(out)
    if not lines:
        return None
    return f'CREATE TABLE IF NOT EXISTS {name} (\n' + ',\n'.join(lines) + '\n);'


def main():
    tables = {}
    for fname in SOURCE_ORDER:
        path = os.path.join(MIGRATIONS, fname)
        if not os.path.exists(path):
            print(f'  ! missing {fname}', file=sys.stderr)
            continue
        src = open(path, encoding='utf-8').read()
        for m in re.finditer(
            r'CREATE TABLE\s+(?:IF NOT EXISTS\s+)?(\w+)\s*\((.*?)\n\)\s*;',
            src, re.S | re.I,
        ):
            name, body = m.group(1), m.group(2)
            ddl = convert_table(name, body)
            if ddl:
                tables[name] = ddl

    # Columns the migrations add separately.
    pw = os.path.join(MIGRATIONS, '004_add_password_hash_to_sales_reps.sql')
    if os.path.exists(pw) and 'password_hash' not in tables.get('sales_reps', ''):
        for m in re.finditer(r'ADD COLUMN\s+(?:IF NOT EXISTS\s+)?(\w+)\s+([\w ()]+)',
                             open(pw).read(), re.I):
            col, typ = m.group(1), translate_type(m.group(2))
            tables['sales_reps'] = tables.get('sales_reps', '').rstrip(';\n') + \
                f',\n  {col} {typ}'

    out = [HEADER]
    for name in sorted(tables):
        out.append(tables[name])
        out.append('')

    # Indexes. Plain columns only -- libSQL has no GIN and no tsvector, so
    # full-text search falls back to LIKE.
    #
    # Every column below was read out of the generated schema rather than
    # assumed. The first draft used appointments.scheduled_date and
    # followups.next_followup_at, which sound right and exist in neither table:
    # appointments has scheduled_start/scheduled_end, and followups keys on
    # scheduled_date. SQLite reported both as "no such column" and created no
    # index at all -- an index on a missing column is not a warning, it is
    # silently absent, so a query that depended on it would have gone to a full
    # table scan with nothing in the logs to say why.
    out.append('CREATE INDEX IF NOT EXISTS idx_leads_status        ON leads(status);')
    out.append('CREATE INDEX IF NOT EXISTS idx_leads_customer      ON leads(customer_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_leads_created       ON leads(created_at);')
    out.append('CREATE INDEX IF NOT EXISTS idx_interactions_cust   ON interactions(customer_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_interactions_lead   ON interactions(lead_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_interactions_when  ON interactions(created_at);')
    out.append('CREATE INDEX IF NOT EXISTS idx_appts_cust          ON appointments(customer_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_appts_start         ON appointments(scheduled_start);')
    out.append('CREATE INDEX IF NOT EXISTS idx_appts_rep           ON appointments(assigned_sales_rep_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_followups_lead      ON followups(lead_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_followups_cust      ON followups(customer_id);')
    out.append('CREATE INDEX IF NOT EXISTS idx_followups_sched     ON followups(scheduled_date);')
    out.append('CREATE INDEX IF NOT EXISTS idx_reps_email          ON sales_reps(email);')
    out.append('CREATE INDEX IF NOT EXISTS idx_reps_status         ON sales_reps(status);')
    out.append('')

    body = '\n'.join(out)

    os.makedirs(OUT_DIR, exist_ok=True)
    target = os.path.join(OUT_DIR, '001_core.sql')
    with open(target, 'w', encoding='utf-8') as f:
        f.write(body)

    if '--print' in sys.argv:
        print(body)

    print(f'  wrote {os.path.relpath(target, ROOT)}')
    print(f'  {len(tables)} tables: {", ".join(sorted(tables))}')
    print()
    print('  deliberately NOT translated:')
    for f, why in SKIPPED.items():
        print(f'    {f}')
        print(f'      {why}')


if __name__ == '__main__':
    main()
