backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Hero", name: "hero", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Subheading", name: "subheading", widget: "string"},
              {label: "Background Image", name: "image", widget: "image"}
            ]}
          - {label: "Featured Vehicles", name: "featured", widget: "list", fields: [
              {label: "Model", name: "model", widget: "string"},
              {label: "Price", name: "price", widget: "string"},
              {label: "Description", name: "description", widget: "text"},
              {label: "Image", name: "image", widget: "image"},
              {label: "URL", name: "url", widget: "string"}
            ]}
          - {label: "Testimonials", name: "testimonials", widget: "list", fields: [
              {label: "Quote", name: "quote", widget: "text"},
              {label: "Author", name: "author", widget: "string"},
              {label: "Rating", name: "rating", widget: "number", default: 5, min: 1, max: 5}
            ]}
  
  - name: "vehicles"
    label: "Vehicles"
    folder: "site/content/vehicles"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Model Year", name: "year", widget: "number"}
      - {label: "Model", name: "model", widget: "string"}
      - {label: "Starting Price", name: "price", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Features", name: "features", widget: "list"}
      - {label: "Specifications", name: "specs", widget: "object", fields: [
          {label: "Engine", name: "engine", widget: "string"},
          {label: "Horsepower", name: "horsepower", widget: "string"},
          {label: "MPG", name: "mpg", widget: "string"},
          {label: "Drive Type", name: "drivetype", widget: "string"},
          {label: "Transmission", name: "transmission", widget: "string"},
          {label: "Seating", name: "seating", widget: "string"}
        ]}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "posts"
    label: "Blog Posts"
    folder: "site/content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "team"
    label: "Team Members"
    folder: "site/content/team"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Bio", name: "body", widget: "markdown"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Phone", name: "phone", widget: "string", required: false}
